import Foundation
import FoundationModels

/// An intelligent DGA evaluator leveraging the new on-device FoundationModels API.
/// This replaces the string matching heuristics used in Go, evaluating domains via 
/// the native Apple Neural Engine.
public struct DGAPredictor {
    
    // We initiate a language model session tailored for lightweight evaluation tasks.
    // Ensure the system has downloaded and supports the relevant FoundationModels model.
    private let session: LanguageModelSession
    
    public init() {
        // Initializes the local session
        self.session = LanguageModelSession()
    }
    
    /// Predicts if a given domain is generated by a DGA algorithm.
    /// - Parameter domain: The domain string to evaluate.
    /// - Returns: True if marked as malicious DGA, false otherwise.
    public func predict(domain: String) async throws -> Bool {
        // Form the prompt for DGA evaluation
        let promptText = """
        Analyze the following domain name: \(domain). 
        Determine if it is a legitimate domain name ('NORMAL') or generated by a Domain Generation Algorithm ('DGA').
        Reply strictly with 'DGA' or 'NORMAL'.
        """
        
        let instructions = Instructions("You are a cybersecurity expert that identifies DGA generated domains.")
        
        // Execute the prediction using `generate()` on the session
        // Depending on actual FoundationModels API, we adapt to the prompt parameters 
        // using the documentation we looked up: Session init and generate
        let response = try await session.generate(from: Prompt(promptText, instructions: instructions))
        
        if response.text.uppercased().contains("DGA") {
            return true
        }
        return false
    }
}
